[[themes]]
name = "Cobalt2"
[themes.palette]
background = "#15232d"
foreground = "#e1efff"
black = "#0050a4"
red = "#ff628c"
green = "#a5ff90"
yellow = "#ffc600"
blue = "#0088ff"
magenta = "#fb94ff"
cyan = "#9effff"
white = "#e1efff"
bright_black = "#193549"
bright_red = "#f44542"
bright_green = "#3ad900"
bright_yellow = "#ff9d00"
bright_blue = "#80fcff"
bright_magenta = "#ff0088"
bright_cyan = "#9effff"
bright_white = "#ffffff"
