# vim:ft=kitty

## name: Cobalt2
## license: MIT
## author: Folke Lemaitre
## upstream: https://github.com/Addeuz/cobalt2.nvim/raw/main/extras/kitty/cobalt2.conf


background #193549
foreground #ffffff
selection_background #0050a4
selection_foreground #ffffff
url_color #3ad900
cursor #ffffff
cursor_text_color #193549

# Tabs
active_tab_background #0088ff
active_tab_foreground #15232d
inactive_tab_background #1f4662
inactive_tab_foreground #5f7e97
#tab_bar_background #142a3a

# Windows
active_border_color #0088ff
inactive_border_color #1f4662

# normal
color0 #000000
color1 #ff628c
color2 #3ad900
color3 #ffc600
color4 #0088ff
color5 #fb94ff
color6 #80fcff
color7 #e1efff

# bright
color8  #0050a4
color9  #ff628c
color10 #3ad900
color11 #ffc600
color12 #0088ff
color13 #fb94ff
color14 #80fcff
color15 #ffffff

# extended colors
color16 #ff9d00
color17 #f44542
