# -----------------------------------------------------------------------------
# Theme: Cobalt2
# Upstream: https://github.com/Addeuz/cobalt2.nvim/raw/main/extras/termux/cobalt2.properties
# -----------------------------------------------------------------------------

background: #193549
foreground: #ffffff

# Normal colors
color0:  #000000
color1:  #ff628c
color2:  #3ad900
color3:  #ffc600
color4:  #0088ff
color5:  #fb94ff
color6:  #80fcff
color7:  #e1efff

# Bright colors
color8:  #0050a4
color9:  #ff628c
color10: #3ad900
color11: #ffc600
color12: #0088ff
color13: #fb94ff
color14: #80fcff
color15: #ffffff

# Extended colors
color16: #ff9d00
color17: #f44542
